
resources:
  repositories: 
    - repository: NodsJS-web-app-with-Kubernetes-and-Helm
      type: github
      name: sincros121/NodsJS-web-app-with-Kubernetes-and-Helm
      ref: master
      endpoint: github.com_sincros121

trigger: none

pool: azure-vm

stages:
- stage: CI
  displayName: Build
  
  jobs:
  - job: Build
    displayName: Build image

    steps:
    - checkout: self
      displayName: Clone latest web-application repo

    - task: Docker@2
      displayName: Docker build
      inputs:
        containerRegistry: 'Private ACR'
        repository: 'bootcamp-app'
        command: 'build'
        Dockerfile: './Dockerfile'
        tags: $(Build.BuildId)

  - job: PushImage
    displayName: Push image
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: Build

    steps:
    - checkout: none
    - task: Docker@2
      inputs:
        containerRegistry: 'Private ACR'
        repository: 'bootcamp-app'
        command: 'push'
        tags: '$(Build.BuildId)'
    
  - job: PackageChart
    displayName: Package and push chart
    dependsOn: PushImage

    steps: 
    - checkout: NodsJS-web-app-with-Kubernetes-and-Helm
      displayName: Clone Helm chart repo

    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: 'k8s-rg'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login -n staslregistry

    - task: DownloadSecureFile@1
      name: stage_values
      displayName: Download chart values file
      inputs:
        secureFile: 'stage-values.yaml'

    - script: |
         helm dependency update ./
      displayName: Update chart dependencies
  
    - script: |
        helm lint ./ -f "$(stage_values.secureFilePath)"
      displayName: Check chart validity

    - script: |
        helm package ./ --version $(Build.BuildId) --destination ./packages
      displayName: Package Helm chart

    - script: |
        helm push ./packages/web-app-chart-$(Build.BuildId).tgz oci://staslregistry.azurecr.io
      displayName: Push Helm package to ACR
    








- stage: Stage_deployment
  displayName: Deployment

  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: CI
  
  variables: 
  - name: ip_address
    value: $(az network public-ip list -g web-app-k8s-resources --query "[?tags.service].ipAddress | [0]" | tr -d '"')

  jobs:
  - deployment: deployToStage
    environment: stage
    strategy:
      runOnce:
        deploy:
          steps:
            
#           - task: Docker@2
#             displayName: Login to private registry
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'login'
          - task: DownloadSecureFile@1
            name: stage_values
            displayName: Download chart values file
            inputs:
              secureFile: 'stage-values.yaml'

          - script: 
              echo $(ip_address)

          - script: |
              helm upgrade --install --namespace stage --create-namespace web-app-stage oci://staslregistry.azurecr.io/web-app-chart --version $(Build.BuildId) -f "$(stage_values.secureFilePath)" --atomic --wait --set ip_address=$(ip_address)

          - script: 
              echo $(ip_address)

#           - script: |
#               docker create -p 8080:8080 --restart always --name wt wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Create application container

#           - script: |
#               docker cp $(System.DefaultWorkingDirectory)/.env wt:/bootcamp-app/
#             displayName: Copy Env file to container appliaction directory

#           - task: Docker@2
#             displayName: Start appliaction container
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'start'
#               container: 'wt'

#           - task: DeleteFiles@1
#             displayName: Delete Env file for working directory
#             inputs:
#               SourceFolder: '$(System.DefaultWorkingDirectory)'
#               Contents: '.env'
          
          


  
# - stage: Prod_deployment
#   displayName: Prod
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   dependsOn: Stage_deployment
  
#   variables: 
#   - group: vault secrets - prod
#   - name: ip_address
#     value: $(az network public-ip show -g weight-tracker-prod-rg -n front-public-ip --query ipAddress | tr -d '"')

#   jobs:
#   - deployment: deployToProd
#     environment:
#       name: prod
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: templates/env-creation-prod.yaml

#           - task: Docker@2
#             displayName: Login to private registry
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'login'

#           - script: |
#               docker rm -f $(docker ps -aq) || true
#             displayName: Delete all previous containers
              
#           - script: |
#               docker pull wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Pull latest application image

#           - script: |
#               docker create -p 8080:8080 --restart always --name wt wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Create application container

#           - script: |
#               docker cp $(System.DefaultWorkingDirectory)/.env wt:/bootcamp-app/
#             displayName: Copy Env file to container appliaction directory

#           - task: Docker@2
#             displayName: Start appliaction container
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'start'
#               container: 'wt'

#           - task: DeleteFiles@1
#             displayName: Delete Env file for working directory
#             inputs:
#               SourceFolder: '$(System.DefaultWorkingDirectory)'
#               Contents: '.env'