
resources:
  repositories: 
    - repository: NodsJS-web-app-with-Kubernetes-and-Helm
      type: github
      name: sincros121/NodsJS-web-app-with-Kubernetes-and-Helm
      ref: master
      endpoint: github.com_sincros121

trigger: none

pool: azure-vm

stages:
- stage: CI
  displayName: Build

  variables:
  - name: HelmDirectory
    value: ./NodsJS-web-app-with-Kubernetes-and-Helm
  
  jobs:
  - job: Build
    displayName: Build image and package Helm chart

    steps:
    - checkout: self
      displayName: Clone latest web-application repo
    
    - checkout: NodsJS-web-app-with-Kubernetes-and-Helm
      displayName: Clone Helm chart repo

    - task: DownloadSecureFile@1
      name: stage_values
      inputs:
        secureFile: 'stage-values.yaml'
    - task: Docker@2
      displayName: Docker build
      inputs:
        containerRegistry: 'Private ACR'
        repository: 'bootcamp-app'
        command: 'build'
        Dockerfile: './Weight tracker - K8S and Helm/Dockerfile'
        tags: $(Build.BuildId)

    - script: |
         helm dependency update $(HelmDirectory)
      displayName: Update chart dependencies
  
    - script: |
        helm lint $(HelmDirectory) -f "$(stage_values.secureFilePath)"
      displayName: Check chart validity

    - script: |
        helm package $(HelmDirectory) --version $(Build.BuildId) --destination $(HelmDirectory)/packages
      displayName: Package Helm chart

  - job: Push
    displayName: Push image and Helm chart to registry
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: Build

    steps:
    - checkout: none
    - task: Docker@2
      inputs:
        containerRegistry: 'Private ACR'
        repository: 'bootcamp-app'
        command: 'push'
        tags: '$(Build.BuildId)'
    
    - script: |
        helm push $(System.DefaultWorkingDirectory)/NodsJS-web-app-with-Kubernetes-and-Helm/packages/web-app-chart-$(Build.BuildId).tgz oci://staslRegistry.azurecr.io

# Had to create a seperate job for the pakcage as azaure devops is masking any 
  # - job: PushPackage
  #   displayName: Push Helm package
  #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #   dependsOn: Build
  #   steps:
  #   - script: |
  #       helm push $(HelmDirectory)/packages/web-app-chart-$(Build.BuildId).tgz "oci://staslRegistry.azurecr.io"
    








# - stage: Stage_deployment
#   displayName: Stage

#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   dependsOn: CI
  
#   variables: 
#   - group: vault secrets - stage
#   - name: ip_address
#     value: $(az network public-ip list -g web-app-k8s-resources --query "[?tags.service].ipAddress | [0]" | tr -d '"')

  # jobs:
  # - deployment: deployToStage
  #   environment:
  #     name: stage
  #     resourceType: VirtualMachine
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
            
#           - task: Docker@2
#             displayName: Login to private registry
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'login'

#           - script: |
#               docker rm -f $(docker ps -aq) || true
#             displayName: Delete all previous containers
              
#           - script: |
#               docker pull wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Pull latest application image
              
              # - script: |
              #     helm upgrade --install --namespace stage --create-namespace web-app-stage oci://staslregistry.azurecr.io/web-app-chart --version $(Build.BuildId) -f stage-values.yaml --atomic  --set ip_address=$(ip_address)


#           - script: |
#               docker create -p 8080:8080 --restart always --name wt wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Create application container

#           - script: |
#               docker cp $(System.DefaultWorkingDirectory)/.env wt:/bootcamp-app/
#             displayName: Copy Env file to container appliaction directory

#           - task: Docker@2
#             displayName: Start appliaction container
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'start'
#               container: 'wt'

#           - task: DeleteFiles@1
#             displayName: Delete Env file for working directory
#             inputs:
#               SourceFolder: '$(System.DefaultWorkingDirectory)'
#               Contents: '.env'
          
          


  
# - stage: Prod_deployment
#   displayName: Prod
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   dependsOn: Stage_deployment
  
#   variables: 
#   - group: vault secrets - prod
#   - name: ip_address
#     value: $(az network public-ip show -g weight-tracker-prod-rg -n front-public-ip --query ipAddress | tr -d '"')

#   jobs:
#   - deployment: deployToProd
#     environment:
#       name: prod
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: templates/env-creation-prod.yaml

#           - task: Docker@2
#             displayName: Login to private registry
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'login'

#           - script: |
#               docker rm -f $(docker ps -aq) || true
#             displayName: Delete all previous containers
              
#           - script: |
#               docker pull wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Pull latest application image

#           - script: |
#               docker create -p 8080:8080 --restart always --name wt wtregistry01.azurecr.io/bootcamp-app:$(Build.BuildId)
#             displayName: Create application container

#           - script: |
#               docker cp $(System.DefaultWorkingDirectory)/.env wt:/bootcamp-app/
#             displayName: Copy Env file to container appliaction directory

#           - task: Docker@2
#             displayName: Start appliaction container
#             inputs:
#               containerRegistry: 'private-registry'
#               command: 'start'
#               container: 'wt'

#           - task: DeleteFiles@1
#             displayName: Delete Env file for working directory
#             inputs:
#               SourceFolder: '$(System.DefaultWorkingDirectory)'
#               Contents: '.env'